create pairing_lokum.py
hashcloak/Lokum pull request #4
Opened 2023-04-13 11:05 UTC by onurinanc

I'll create a submodule for pairing.py, pairing_cp6_782.py, test_pairing.py and test_pairing_cp6_782.py later. It's a commit and PR to show pairing_lokum.py

2023-04-13 12:05 UTC, Mikerah commented
Let's go 🚀

2023-06-08 16:56 UTC, Mikerah requested changes
- Add more detailed comments in the sage code in order to better guide not only yourself but other readers of the code on how to implement this from scratch
- Shouldn't the actual cairo code be in the starkacy repo?

2023-06-13 10:20 UTC, onurinanc commented
- For the sage code, I'll add more guide
- For the Cairo code, now I'll open a new branch in Starkacy and add the code in there

2023-07-07 05:19 UTC, Mikerah requested changes

2023-07-07 05:19 UTC, Mikerah commented on pairing_cp6_782.py
Was this file changed from the original one? If so then, we should specify which parts have been changed and maybe change the names of the functions to reflect our own curve

2023-07-26 13:53 UTC, onurinanc commented on pairing_cp6_782.py
No, its the same file

2023-07-26 14:17 UTC, Mikerah approved these changes

2023-07-27 08:43 UTC, merged